### PR TITLE
Use the glossaries-extra package for abbreviations

### PR DESCRIPTION
**Pull request by haggaie**
Generate abbreviation list similar to the existing one using the glossaries-extra package. The code generates first-use explanations for acronyms in text, and a sorted glossary table.

Issue: #18

### CODE REVIEW

**Comment by eyalroz** [comment]
Hello Haggai, 

Can you elaborate somewhat on the motivation for this change and what the difference is like in the final PDF?

**Comment by haggaie** [comment]
I was using this package mainly for generating the explanation for acronyms on the first time they are used in the text. In the patch I tried demonstrating it with the QED acronym. The first it is used in the text, it the macro expands to an elaborate version:
image

but the next time the it is used the short version gets printed:
image

Apart from that, the list of abbreviations itself is generated automatically, with page numbers of where each term or acronym is used:
image

It is also possible to have the list of abbreviations include only those that appear in the text, though I didn't do that in this patch as the existing example didn't use all the abbreviations.

I thought it might be useful for others, as you had an open issue to incorporate something like this.

**Comment by eyalroz** [comment]
Ok, so, I like this in general, but:

1. I don't want to mix up the the text regarding `\qed` with a use of the abbreviations mechanism, because I think that might confuse people into thinking the issue of how to end proof environments is somehow related to using the glossaries.
2. If the document class is used with `noabbrevs`, then the glossaries-extra package should not be required and `\gls` should not work...
3. It may be a good idea to actually drop the `noabbrevs` and actually have one or two abbreviations. But - not QED...

Would you like to address this or shall I?

**Comment by haggaie** [comment]
Sure. (2) and (4) are conflicting though, don't they? Should I change the class to remove `noabbrevs` and always depend on `glossaries-extra`? This way `\gls` macros will always work.

**Comment by eyalroz** [comment]
@haggaie : So, the branch is ready.  I don't want `\gls` to always work. If the author doesn't want the document class to generate a list of abbreviations, but _does_ want to use the glossaries/glossaries-extra package , i.e. have `\gls` entries - they can't just `\usepackage{}`.

Have a look at how I've done this on the branch. And actually I've also taken care of (3.), so not that much work left to do. I also need to add a couple more items...

6. Make sure longer acronyms/abbreviations or longer descriptions are handled properly and don't run off the page.
7. Double-check the format makes sense w.r.t. placement on the page.

**Comment by eyalroz** [comment]
Also, closing this one, please create a new PR against the [abbrevs branch](https://github.com/eyalroz/technion-iit-thesis/tree/abbrevs-2022-01).

**Comment by eyalroz** [comment]
... oh, I might do a bit of force-pushing of some changes, so if you've already pulled, you might need to rebase. Sorry :-(

**Pull request closed without merging**
